apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata: 
  name: delta-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      external:
        type: route
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
